version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ec2-user
      WORDPRESS_DB_PASSWORD: docker
      WORDPRESS_DB_NAME: mysql
    volumes:
      - /efs/lucasalves/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: ec2-user
      MYSQL_PASSWORD: docker
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /efs/lucasalves/db:/var/lib/mysql

volumes:
  wordpress:
  db: