version: '3.4'
services:
        db:
                image: mysql:5.7.22
                command: mysqld --default_authentication_plugin=mysql_native_password
                environment:
                        TZ: America/Recife
                        MYSQL_ROOT_PASSWORD: dockeraws
                        MYSQL_USER: lucas
                        MYSQL_PASSWORD: lucas00
                        MYSQL_DATABASE: wordpress
                ports:
                        - "3308:3306"
        wordpress:
                image: wordpress:latest
                volumes:
                        - ./config/php.conf.uploads.ini:/local/etc/php/config.d/uploads.ini
                        - ./wp-app:/var/www/html
                environment:
                        TZ: America/Recife
                        WORDPRESS_DB_HOST: db
                        WORDPRESS_DB_NAME: wordpress
                        WORDPRESS_DB_USER: root
                        WORDPRESS_DB_PASSWORD: lucas00
                ports:
                        - 80:80
                depends_on:
                        - db




